# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbaa340de5c39595fab757604bcc4e8a192c6b81576fb6b52027f937db708f64b4eaf76543ee0fc904beffbfb9f29c0bf85fc112a49427b74343b1010a2c2abb

test:
  secret_key_base: 055bc1a7573fcd211698194eaa1a1d814e48bb90a1e02ab4031a66cd998d89f1357bfa2695a54b9e392ecc4b8ba575af0be17facdf357d34584fc9c3f8ac4e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
